# Generated by Django 4.0.6 on 2022-09-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('applicant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('country', models.TextField()),
                ('status', models.TextField(default='pending')),
                ('created_dttm', models.TimeField(default='10:37:41')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField()),
                ('client_key', models.TextField()),
                ('applicant_status', models.TextField()),
                ('processed_dttm', models.DateTimeField()),
            ],
        ),
    ]
