# Generated by Django 4.0.6 on 2022-09-09 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='applicant_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='created_dttm',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 20, 0, 36, 6177)),
        ),
    ]
