# Generated by Django 4.0.6 on 2022-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_applicants_applicant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='created_dttm',
            field=models.DateTimeField(default='09/09/22 20:17:20'),
        ),
    ]
