# Generated by Django 4.0.6 on 2022-09-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_applicants_created_dttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='created_dttm',
            field=models.DateTimeField(default='09/09/22/09/2022 20:19:12'),
        ),
    ]
